
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    360.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    112.0,
    739.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1378.999267578125,
    165.9998779296875,
    image=image_image_3
)

canvas.create_text(
    394.0,
    64.0,
    anchor="nw",
    text="Face Recognition DTI",
    fill="#FFFFFF",
    font=("Inter SemiBold", 48 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1036.0,
    y=604.0,
    width=180.0,
    height=64.0
)

canvas.create_text(
    604.0,
    345.0,
    anchor="nw",
    text="atau",
    fill="#FFFFFF",
    font=("Inter Regular", 32 * -1)
)

canvas.create_text(
    872.0,
    293.0,
    anchor="nw",
    text="Masukkan token:",
    fill="#FFFFFF",
    font=("Inter Regular", 24 * -1)
)

canvas.create_rectangle(
    795.0,
    346.0,
    1155.0,
    426.0,
    fill="#20293C",
    outline="")

canvas.create_text(
    213.0,
    153.0,
    anchor="nw",
    text="Scan QR Code:",
    fill="#FFFFFF",
    font=("Inter Regular", 24 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    304.0,
    386.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
