
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#2F3B52")


canvas = Canvas(
    window,
    bg = "#2F3B52",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0000610351562,
    331.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    112.0,
    739.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1371.9444580078125,
    157.40966796875,
    image=image_image_3
)

canvas.create_text(
    343.0,
    106.0,
    anchor="nw",
    text="Registrasi Berhasil!",
    fill="#FFFFFF",
    font=("Inter SemiBold", 64 * -1)
)

canvas.create_text(
    492.0,
    479.0,
    anchor="nw",
    text="Dava Aditya Jauhar",
    fill="#FFFFFF",
    font=("Inter Medium", 32 * -1)
)

canvas.create_text(
    492.0,
    529.0,
    anchor="nw",
    text="0531194000030",
    fill="#FFFFFF",
    font=("Inter Medium", 32 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=550.0,
    y=609.0,
    width=180.0,
    height=64.0
)
window.resizable(False, False)
window.mainloop()
