
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    360.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    112.0,
    739.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1378.999267578125,
    165.9998779296875,
    image=image_image_3
)

canvas.create_text(
    57.0,
    228.0,
    anchor="nw",
    text="Rekam\nWajah",
    fill="#FFFFFF",
    font=("Inter SemiBold", 48 * -1)
)

canvas.create_text(
    57.0,
    365.0,
    anchor="nw",
    text="Pastikan anda tidak menggunakan\nkacamata, masker, atau atribut\nlainnya",
    fill="#FFFFFF",
    font=("Inter Regular", 20 * -1)
)

canvas.create_text(
    1051.0,
    359.0,
    anchor="nw",
    text="/10",
    fill="#FFFFFF",
    font=("Inter SemiBold", 96 * -1)
)

canvas.create_text(
    993.0,
    359.0,
    anchor="nw",
    text="1",
    fill="#FFFFFF",
    font=("Inter SemiBold", 96 * -1)
)

canvas.create_text(
    1045.0,
    257.0,
    anchor="nw",
    text="Foto",
    fill="#FFFFFF",
    font=("Inter SemiBold", 48 * -1)
)
window.resizable(False, False)
window.mainloop()
